title: Buzzed Bunnies
author: Doc_Inks
email: 
description: >-
  A Collection of Buzzed, Baked and Bewildered Bunnies 
    - Subscribe for our NFT Drop
    - Physical Collectible Toys
    - Events, Promos, Giveaways & More



social:
  twitter:
  facebook: 
  instagram:
  github: 
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
